name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "github.event_name - ${{ github.event_name }} "
      - run: echo "runner.os         - ${{ runner.os }}         "
      - run: echo "github.ref        - ${{ github.ref }}        "
      - run: echo "github.repository - ${{ github.repository }} "
      - run: echo "github.workspace  - ${{ github.workspace }}  "
      - run: echo "job.status        - ${{ job.status }}        "


      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}


      # - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      # - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      # - name: Check out repository code
      #   uses: actions/checkout@v3
      # - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      # - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      # - run: echo "workspace is ${{ github.workspace }}"
      # - name: List files in the repository
      #   run: |
      #     ls ${{ github.workspace }}
      # - run: echo "ğŸ This job's status is ${{ job.status }}."
